name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate articles.json
        run: node generate.js

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync HTML Files to S3
        run: |
          aws s3 sync ./ s3://danielcherney.com --exclude "*.css" --exclude "*.js" --exclude "*.json" --delete --cache-control "public, max-age=31536000"

      - name: Sync CSS Files to S3
        run: |
          aws s3 sync ./css/ s3://danielcherney.com/css/ --content-type "text/css" --delete --cache-control "public, max-age=31536000"

      - name: Sync JS Files to S3
        run: |
          aws s3 sync ./js/ s3://danielcherney.com/js/ --content-type "application/javascript" --delete --cache-control "public, max-age=31536000"

      - name: Sync JSON Files to S3 with no-cache
        run: |
          aws s3 sync ./ s3://danielcherney.com --exclude "*" --include "articles.json" --content-type "application/json" --delete --cache-control "no-cache"

      - name: Invalidate CloudFront Cache
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          for FILE in $CHANGED_FILES; do
            aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/$FILE"
          done
